services:
  db:
    image: postgres:16
    container_name: kamecol-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kamecol_dev
      POSTGRES_USER: kamecol
      POSTGRES_PASSWORD: kamecol_pass
    ports:
      - "5432:5432"
    volumes:
      - kamecol_pgdata:/var/lib/postgresql/data

volumes:
  kamecol_pgdata: